# Generated by Django 4.0.6 on 2022-07-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimationapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tauxnatalitemortalite',
            old_name='manifest',
            new_name='fichier',
        ),
    ]
