# Generated by Django 4.0.6 on 2022-07-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimationapi', '0002_rename_manifest_tauxnatalitemortalite_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculeDemandeInterieure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalculeProductionDomestique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeDepenseCapitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeDepenseCourante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeDepensePublique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeExportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeImportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeInvestissementPrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportationNettesPays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopulationActiveOffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopulationProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopulationTotalProvinceApresMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReellePopulationProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TauxCroissanceProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TauxMigrationProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
