# Generated by Django 4.0.6 on 2022-12-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimationapi', '0005_donneeproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpotDGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('taux_croissance', models.CharField(max_length=3)),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
