# Generated by Django 4.0.6 on 2022-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimationapi', '0006_impotdgi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpoExpoDGDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='files')),
                ('taux_exportation', models.CharField(max_length=3)),
                ('taux_importation', models.CharField(max_length=3)),
                ('date_heure_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_envoie', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
