# Generated by Django 4.0.6 on 2022-12-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimationapi', '0007_impoexpodgda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impotdgi',
            name='taux_croissance',
        ),
    ]
