# Generated by Django 4.0.6 on 2022-12-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimationapi', '0008_remove_impotdgi_taux_croissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impoexpodgda',
            name='taux_exportation',
        ),
        migrations.RemoveField(
            model_name='impoexpodgda',
            name='taux_importation',
        ),
    ]
